### ISSUE TITLE
can't connect wallet with uniswap

### ISSUE THREAD

**Issue by guangxingmao** [AlphaWallet/alpha-wallet-android#2215] opened 2021-11-09 08:52 UTC
Dapp : http://app.uniswap.org,
The first time I use it, I can connect my wallet normally, but I can't connect my wallet after I exit it several times and open it again

**Comment by colourfreak** [comment] 2021-11-09 14:54
Do you use Uniswap on Ethereum Mainnet or other networks? @guangxingmao

**Comment by guangxingmao** [comment] 2021-11-11 03:04
> Do you use Uniswap on Ethereum Mainnet or other networks? @guangxingmao
yes, I use uniswap on Ethereum Mainnet

**Comment by colourfreak** [comment] 2021-11-12 09:19
Can you share a screenshot or screen record?

**Comment by JamesSmartCell** [comment] 2021-11-15 04:04
Can you update from PlayStore and see if the issue is resolved?

**Comment by guangxingmao** [comment] 2021-11-15 06:19
https://user-images.githubusercontent.com/19208420/141732145-b77bfa0e-9719-4406-a55d-67c190e4f031.mp4

**Comment by guangxingmao** [comment] 2021-11-15 06:20
![1201636957057_ pic](https://user-images.githubusercontent.com/19208420/141732182-2376ecb5-4f19-427a-8e6e-9951462b0819.jpg)

**Comment by guangxingmao** [comment] 2021-11-15 06:21
> Can you update from PlayStore and see if the issue is resolved?

yes,but the problem persists.

**Comment by JamesSmartCell** [comment] 2021-11-15 21:33
Thanks for checking; I will investigate further

**Comment by JamesSmartCell** [comment] 2021-11-16 05:58
@guangxingmao can you try using the option 'Clear Browser Cache' in the hamburger menu, then call Reload once it's finished.

I managed to reproduce the issue, and fixed it this way. I couldn't find how to detect it from the code side.

**Comment by JamesSmartCell** [comment] 2021-11-17 01:58
We have has another person report this issue, it was fixed via 'clear browser cache'. Now we know the solution we'll work on an automatic fix.

**Comment by guangxingmao** [comment] 2021-11-17 06:49
> We have has another person report this issue, it was fixed via 'clear browser cache'. Now we know the solution we'll work on an automatic fix.
ok,tks

**Comment by JamesSmartCell** [comment] 2021-11-17 07:56
Did doing 'clear browser cache' then reload work?

**Comment by colourfreak** [comment] 2021-11-17 08:02
Reveal the menu in the top right corner, then select this item. @guangxingmao 

![2021-11-17 08 59 38](https://user-images.githubusercontent.com/51817359/142159682-951ff1b0-d0db-4d8c-91cd-4918e4fca5ff.jpg)

**Comment by guangxingmao** [comment] 2021-11-22 02:06
> Reveal the menu in the top right corner, then select this item. @guangxingmao
> 
> ![2021-11-17 08 59 38](https://user-images.githubusercontent.com/51817359/142159682-951ff1b0-d0db-4d8c-91cd-4918e4fca5ff.jpg)

tks

**Comment by guangxingmao** [comment] 2022-01-05 10:46
Yes, I try to clear browser cache, but it still can't connect wallet.

https://user-images.githubusercontent.com/19208420/148204709-8f43b24c-f98c-47fb-819b-fd8d054115ba.mp4

Other dapps work  well, only uniswap can't connect wallet

**Comment by JamesSmartCell** [comment] 2022-01-14 04:13
@guangxingmao we are currently investigating this - we have a partial fix for it, but the root cause is an update from the Uniswap team which also breaks many other crypto wallets.

We are developing the fix; you can track the progress here: #2303

**Closed** 2022-01-21 01:18 UTC
