### ISSUE TITLE
Display TokenScript file signature verification result

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#679] opened 2019-04-25 08:34 UTC
@colourful-land We currently display "VERIFIED", "UNVERIFIED" and "DEBUG" at the top right with a green lock for "VERIFIED" and red "unlocked" for the other 2. How are we going to change it with signature verification?

Something like this?

```
canonicalized = extension == ".tsml"
if canonicalized
  switch callSignVerificationApi()
  case pass:
    display = "VERIFIED"
  case fail:
    display = "UNVERIFIED"
  case apiNotAvailableOrDown:
    display = "UNVERIFIED"
else
  display = "DEBUG"
end
```

Do we need to indicate if there is a sig but it failed verification. Or is that just "UNVERIFIED"?

And what do we show while the signature is still being verified?

**Comment by colourful-land** [comment] 2019-04-25 13:52
Let's toy with some ideas.

# First, unverified files.

Intuitively, the unverified tokenscript tsml file should not be used, even to parse the token name may not be necessary. The same for invalid tsml file (XML validation). So the two cases can be merged to one. For this case, we can display a permanent banner in Wallet screen which says:

"dai.tsml is found but it doesn't work."

Clicking the banner gets the user the technical briefing (signature error or validation error) and the choice of "deleting the file". If the user clicks OK, the file is deleted. If the user clicks "Cancel", the banner stays.

Now let's put that idea to test. Note that there might be a few reasons the message shows up.

1. the tsml is simply  dai.canonicalized.xml renamed. This should not happen if our tutorial is correct.
2. the tsml is illy placed there by a fishing attempt. In anrdoid, it could be another app which acquired storage read/write permission and was intended to fish the user. In iOS, since an app can't place a file in another app's storage, the 'fishing tool' must be a desktop app. This case is extremely unusual but must be defended against.
3. we have changed the trust model (e.g. allow signature without certificates, where the smart contract provides certificates), or that we no longer support the old namespace (2019/04). This is probably the usual case. 

Let's say the first case won't happen. in the 2nd and 3rd case, the banner idea seems to work.

# then, debug files

An interesting problem arises when a file in debug mode claimed the same token-originating smart contract address. Normally, when two TokenScript files claim to manage the same token (declaring the same smart contract as its origin), we will ask the user which one to install, and only keep one alive. But in the debug mode, the file is placed directly, bypassing the app's checking mechanism, even if there was an on-disk tokenscript (tsml)

There are a few approaches.

1. Use the debug file, and show a debug label. Use the on-disk tokenscript (tsml) if the user turns off debug mode.

2. Show 2 tokens side by side, for one actual token. This is not only confusing but breaks the web integration..

# the visual approach for custodian tokens and debug tokens

Custodian tokens should be clearly marked as custodian, and the word "custodian" must appear, as this is the point no confusion is allowed. This is visually difficult to arrange given we already have lots of labels on tokens. @farrahfazirah's attention is needed on this.

Debug token also need to be clearly marked - a naïve designer would think that a visual cue is enough, but that is on the assumption that the user enabled debug mode himself!! I would even put a watermark with a pattern of "debug mode, do not trust", similar to this:

![brunei_10_2008-00-00_b24c_f](https://user-images.githubusercontent.com/548435/56740638-a87c3f80-67b4-11e9-913b-5eeacaab0012.jpg)

In other words, you need words. A visual cue is not enough.

# What about the file still being verified.

This only happens if we use endpoints to verify the signature, as normally signature verification is lightning fast. I suppose we can simply show an hourglass until the signature is verified. This is acceptable as long as the signature is not verified every time. That is, you might take the value of

    <ds:DigestValue>H8aA0kTpIrewwT78gPeoa/tAluLATSPtbjaHwl10I5w=</ds:DigestValue>

Then as long as the tokenscript's DigestValue remain unchanged, and the record shows the endpoint noded over the signature, the endpoint is not accessed again. If you stick to this, an hourglass is acceptable.

# What about the verified token

A small line of text saying "[the info is] as trustworthy as makerdao.com" is needed, as a label, in the token view. We may eventually reduce or weaken this as user gets familiar with TokenScript, maybe in a few years, but it's needed at the beginning when the user needs to be "trained" to be aware that TokenScript runs in a different security level than dapp websites.

**Comment by colourful-land** [comment] 2019-04-26 07:26
Possible status of TokenScript files.

- not in working condition - signature verification failed, or invalid against 𝑎𝑛𝑦 schema we know of (meaning we should ship 2019/04, 2019/05.... schemas)

- in an unsupported outdated format - signature verified, file valid against 𝑎 schema we know of (historical), but on the schema current app supports.

- Is a debug file (xml) - potentially taking precedence over an existing tsml file on the user's mobile.

- signature verified, valid and supported.

**Comment by hboon** [comment] 2019-04-26 07:40
How about this:

```
if validatedAgainstSchemaSuccessfuly
  switch callSignVerificationApi()
  case pass:
    title = "VERIFIED" aka "verified successfully"
    renderWithTokenScript()
  case fail:
    title = "VERIFICATION FAILED"
    renderDefaultViewWithoutTokenScript()
  case apiNotAvailableOrDown:
    title = "UNVERIFIED"
    if debug
      renderWithTokenScript()
    else
      renderDefaultViewWithoutTokenScript()
    end
  end
else
  title = "Not in working condition"
  renderDefaultViewWithoutTokenScript()
end

if debug || extension != ".tsml"
  title = "DEBUG" + title
end
```

In the iOS app, there is no explicit debug mode, should we have one? Currently, anyone can AirDrop a file to the user (if the user has enabled AirDrop based on permissions managed by the OS), but iOS will ask the user to confirm before saving the file, so our app assumes that by the time it sees the file, the user has expressed their approval and we save it into the app's directory as an override file

> In iOS, since an app can't place a file in another app's storage, the 'fishing tool' must be a desktop app. This case is extremely unusual but must be defended against.

This is only possible on iOS if the user jailbreaks the device himself or an attacker jailbreaks it. Do we need to guard against that? Or is it just safe to cover our bases anyway?

**Comment by hboon** [comment] 2019-04-28 07:22
@colourful-land 

> an error banner says 'xxx.xml is not valid'. If in debug mode, the message is in wallet screen. Otherwise, the message is on the TokenIconified and TokenView

There can be more than 1 broken TokenScript file. e.g. when the user copies a number of TokenScript files onto external storage on Android. If we want to show this in banner that is always visible in the Wallet tab, how about a short banner that when tapped, shows a list of messages? If there's only 1 broken TokenScript file, we can just show that 1 message.

> green-label "as trustworthy as www.makerdao.com". If the certificate has expired, yellow-label "was as trustworthy as www.makerdao.com by xxxx"‡

Are we expecting this validator API to provide these information?: <https://github.com/AlphaWallet/alpha-wallet-android/pull/683>

**Comment by colourful-land** [comment] 2019-04-28 07:27
@hboon can you show up on TokenScript integrity UX meeting on Tuesday where we do a focused discussion on this? @farrahfazirah must show up

**Comment by hboon** [comment] 2019-04-28 07:32
> can you show up on TokenScript integrity UX meeting on Tuesday

@colourful-land yes

**Closed** 2019-10-02 14:01 UTC
