### ISSUE TITLE
Wallet fails to detect NFTs with duplicating addresses on ETH and Polygon

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-android#2365] opened 2022-01-28 10:52 UTC
The user has imported a wallet with existing NFTs on Polygon using the Motorola g6 Android9, retail version of the wallet. It doesn't auto-detect his NFTs, but he sees them in OpenSea when connects with AW.

Public adress:
0x291252119f196fc9d876d6a6b2155a2520d1000f

Polychain Monsters Contract address Polygon ERC721:
0x85F0e02cb992aa1F9F47112F815F519EF1A59E2D
5 nfts total on this chain.

CryptoCubers #1822 Contract address Polygon ERC1155:
0x2953399124F0cBB46d2CbACD8A89cF0599974963
3 nfts total on this chain.
------------------------
When we try to add the tokens manually (add/hide token), we go through the scanning process, but the scan stops when it finds the same duplicate addresses on Ethereum.

1. https://etherscan.io/address/0x85F0e02cb992aa1F9F47112F815F519EF1A59E2D 
2. https://etherscan.io/address/0x2953399124F0cBB46d2CbACD8A89cF0599974963 (this is actually a wallet, what is the chance of that)

The wallet stops searching and we are unable to add the tokens at all. Can we implement some solution that skips 0 values and continues the scan for edge cases like this?

I tested on iOS as well. When we import the wallet the first one is found automatically (properly assigned to the Polygon collection) and the second one finds the collection on Polygon, but displays 0 NFTs instead of 3.

Thank you for checking!

**Comment by JamesSmartCell** [comment] 2022-01-29 22:41
Nice catch, I'll check it

**Comment by JamesSmartCell** [comment] 2022-01-30 03:05
I'll make the following solution which I think is consistent with our UI (@colourfreak what do you think?):

Add a tokens view the same as in the main wallet view, so when each token from each chain appears, you'll see it as it would appear in your wallet, with a chain icon so you can see which chain it is, together with any balance you have on that wallet in a familiar fashion.

These will be on a square checkbox list (multi select) so you can select whichever tokens you want to add into the wallet, then click the 'save tokens' button as normal.

**Comment by hboon** [comment] 2022-01-30 04:41
@JamesSmartCell  The UI you suggested is nice for other reasons (it's useful if we adopt the philosophy of not auto-detecting/adding tokens discovered in the user's wallet, which is not what we have now). But why is it necessary here?

**Comment by JamesSmartCell** [comment] 2022-01-30 06:09
Multiple tokens can be shown simultaneously on the screen ... it's a natural choice.

The tokens are normally auto-discovered but this is a backup I guess.

**Comment by JamesSmartCell** [comment] 2022-01-30 09:10
Like this:

Except with a 'check' button prefixing each token, and a type marker.

![Screenshot_20220130-200757_AlphaWallet](https://user-images.githubusercontent.com/12689544/151693613-684f4905-9fae-4fa2-a001-f0c1d910fbea.jpg)

**Comment by hboon** [comment] 2022-01-30 09:57
Oh. Are you referring to the UI when adding a token manually? The original issue is about the token (balance) not being detected automatically, isn’t it?

As for manually adding the token, our existing UI lets the user choose a chain so it can be addressed by the user too. Just being wary about adding features unnecessarily.

**Comment by JamesSmartCell** [comment] 2022-01-30 11:23
Two issues in one, the first is (should be) solved - that is the token detection is improved.

The second is, yes you can switch chains however this functionality is not as obvious as it used to be.

This change simplifies the 'Add Token' code and improves functionality. I originally wrote the Token adapter to be almost 'drag and drop' so it was trivial to add now there's less places for code to be maintained.

**Comment by JamesSmartCell** [comment] 2022-01-30 11:35
> Oh. Are you referring to the UI when adding a token manually? The original issue is about the token (balance) not being detected automatically, isn’t it?
> 
> As for manually adding the token, our existing UI lets the user choose a chain so it can be addressed by the user too. Just being wary about adding features unnecessarily.

I didn't read it like that; the issue is that on Android at least, it runs through each chain and stops when it finds the first token on the chain. You _can_ set the preferred chain through the filter button, but this may not be obvious. If the available tokens are all shown, the users will always be able to get the token they want.

The address 0x85F0e02cb992aa1F9F47112F815F519EF1A59E2D has a token on Etherem, BSC and Polygon.

**Comment by hboon** [comment] 2022-01-30 14:55
> I didn't read it like that; the issue is that on Android at least, it runs through each chain and stops when it finds the first token on the chain.

Ah, I see what you mean. We can read it as either problem.

But do you think that if we can fix the auto-detection issue, it'll be good enough? Anyway, they are separate issues. It seems like iOS has the same 2 issues.

**Comment by JamesSmartCell** [comment] 2022-01-30 22:33
@colourfreak Here's my draft implementation:

![Screenshot_20220131-093146_AlphaWallet](https://user-images.githubusercontent.com/12689544/151720667-b5f1b313-8ee8-4b61-994e-ea8f2ed3f99a.jpg)

It shows progress, scanning all the chains while it's in action.

**Closed** 2022-02-01 01:04 UTC
