### ISSUE TITLE
the QR code scanner on browser tab doesn't recognise URLs

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1253] opened 2020-03-23 23:49 UTC
Reproduce.

1. On your PC, go to https://www.qrcode-monkey.com/
2. Use your mobile to scan the QR code there.
3. get the message "Invalid scan result"

Expected:

3. The browser launches the website  https://www.qrcode-monkey.com/

**Comment by JamesSmartCell** [comment] 2020-03-24 02:37
It has been fixed in the past. But possible PR didn't go through and got closed.

**Comment by JamesSmartCell** [comment] 2020-03-24 02:39
Works on latest master branch

**Closed by JamesSmartCell** 2020-03-24 02:39 UTC
Labels: bug

**Comment by James-Sangalli** [comment] 2020-03-24 02:43
Works in iOS

**Comment by James-Sangalli** [comment] 2020-03-24 02:57
Duplicate of https://github.com/AlphaWallet/alpha-wallet-android/issues/1177
