### ISSUE TITLE
Showing wrong wallet in Settings tab after backing up legacy/private key wallet

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#2427] opened 2022-02-28 07:06 UTC
(Marking higher priority in case this breaks key management)

1. Make sure active wallet is a legacy (imported with private key) wallet
2. Verify wallet address is say, 0xb0b
3. Settings tab
4. Tap Upgrade key security (should say Not Locked)
5. Tap Upgrade key security
6. Says "Unable to upgrade key: Enable screenlock on phone"
7. Tap Continue
8. Enable screenlock (but not fingerprint/Face recognition)
9. Already in Settings tab
10. Tap Upgrade key security (should say Not Locked)
11. Tap Upgrade key security
12. Prompted for lockscreen password
13. Enter

Expected:

14. Settings > Change / Add Wallet still says 0xb0b

Observed:

14. Settings > Change / Add Wallet no longer says 0xb0b. It happens to show the address of the first wallet in the list of watched wallets (for my testing)

**Comment by justindg** [comment] 2022-02-28 18:41
@hboon @JamesSmartCell - unfortunately I am unable to replicate this issue after testing with a couple of wallets

Here is how I tested:

1. From fresh install, create a new wallet and watch a random wallet e.g. `vitalik.eth` to ensure we have two kinds of wallets
2. Ensure your phone has no screen lock (`Device Settings` > `Lock Screen` > `Screen lock type` > `None`). This is so we get the `Upgrade key security` menu in AlphaWallet
3. Head back to AlphaWallet and import a legacy wallet
4. Go to Settings tab
5. Tap `Upgrade key security (Not Locked)`
6. Tap `Upgrade key security` button
7. Says `Unable to upgrade key: Enable screenlock on phone`
8. Tap `Continue`
9. Go to `Device Settings` > `Lock Screen` > `Screen lock type` > `Password` and add a password
10. Head back to AlphaWallet. You should find yourself in Settings screen.
11. Tap `Upgrade key security (Not Locked)`
12. Tap `Upgrade key security button`
13. Prompted for lockscreen password
14. Enter password
16. Result: legacy wallet address is still displayed under `Change / Add Wallet`

**Comment by JamesSmartCell** [comment] 2022-02-28 21:42
I also followed your guide exactly, I entered 1 watch wallet previously.

All steps exactly as you described but final works as per your 'expected'.

**Comment by hboon** [comment] 2022-03-01 07:20
Only difference I can tell is, you have:

> 1. Create a new wallet

and I have:

> 1. Make sure active wallet is a legacy (imported with private key) wallet

Can we try that if you haven't?

**Comment by JamesSmartCell** [comment] 2022-03-01 17:46
@hboon can you reproduce this following the steps above? If so can you post a video in case we're not doing some step that you have?

**Comment by hboon** [comment] 2022-03-02 05:05
Sure:

https://user-images.githubusercontent.com/56189/156298669-2c9bbc72-de78-47eb-8837-82eace61b0a5.mp4

**Comment by JamesSmartCell** [comment] 2022-03-02 05:53
Nope, I follow the exact same sequence with fresh install and it works correctly for me.

In order to see what's going on locally on your phone you're going to have to help me debug this. I can give you a debug build (or you can build AW from source) and give me a Logcat dump.

**Comment by JamesSmartCell** [comment] 2022-03-08 09:54
Still unable to reproduce issue, but fixed a related issue that could occur in a similar way while investigating.

**Comment by seabornlee** [comment] 2022-03-23 03:26
Me neither. But I think the `findWallet` can return the first wallet in a particular situation that may cause this.
![image](https://user-images.githubusercontent.com/735708/159617900-1112c381-6ae7-4186-b3c0-64b182cdf926.png)

**Comment by JamesSmartCell** [comment] 2022-03-29 06:37
Yes, that's when it can't find a matching wallet.

It's possible this is now fixed; I found what could have been the culprit which was an old workaround that still had roots in the app from a long time ago. The issue that caused the workaround to be added was fixed properly, and I only just removed the last traces of the workaround.

**Comment by JamesSmartCell** [comment] 2022-04-02 23:26
@hboon can you see if it's possible to reproduce this issue? It should be fixed

**Comment by hboon** [comment] 2022-04-04 02:38
It shows this after doing step (11) "Tap Upgrade key security" in https://github.com/AlphaWallet/alpha-wallet-android/issues/2427#issue-1153730682 (i.e it doesn't go to step 11)

<img width='200' src='https://user-images.githubusercontent.com/56189/161464836-2636e207-68a3-4b89-9e9b-048fba57dde0.JPG'>

**Comment by JamesSmartCell** [comment] 2022-04-04 07:33
Still unable to reproduce even with my Huawei. Can you try the same thing on an emulator? If you have AndroidStudio installed?

Here's what I do:

1. Disable screen lock
2. Open Alphawallet which has 1 watch wallet.
3. import key from MM
4. attempt to back up (see the unable to back up message)
5. open settings, switch on screen lock and enter screen lock (twice)
6. switch back to AW
7. upgrade key security
8. type the key code
9. see the green tick.

I also repeated by attempting to back up:

1. back up key
2. type screen lock code
3. type password
4. save the JSON file
5. confirm I saved
6. green tick

**Comment by hboon** [comment] 2022-04-05 02:55
Trying with my Huawei:

Ah, maybe the key is not accessible? I get this after I have set the lock screen password and try tap "Upgrade key security":

```
2022-04-05 10:49:25.661 27773-28551/? W/System.err: com.alphawallet.app.entity.ServiceErrorException: Wallet can not read encrypted key; re-import required.
2022-04-05 10:49:25.661 27773-28551/? W/System.err:     at com.alphawallet.app.service.LegacyKeystore.getLegacyPassword(LegacyKeystore.java:50)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at com.alphawallet.app.service.KeyService.upgradeKey(KeyService.java:567)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at com.alphawallet.app.service.KeyService.upgradeKeySecurity(KeyService.java:350)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at com.alphawallet.app.viewmodel.BackupKeyViewModel.lambda$upgradeKeySecurity$1$com-alphawallet-app-viewmodel-BackupKeyViewModel(BackupKeyViewModel.java:125)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at com.alphawallet.app.viewmodel.BackupKeyViewModel$$ExternalSyntheticLambda9.call(Unknown Source:6)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-04-05 10:49:25.662 27773-28551/? W/System.err:     at java.lang.Thread.run(Thread.java:929)
```

If I go to sign in the dapp browser, I get this:

```
2022-04-05 10:50:00.600 27773-28551/? W/System.err: com.alphawallet.app.entity.ServiceErrorException: Wallet can not read encrypted key; re-import required.
2022-04-05 10:50:00.600 27773-28551/? W/System.err:     at com.alphawallet.app.service.LegacyKeystore.getLegacyPassword(LegacyKeystore.java:50)
2022-04-05 10:50:00.600 27773-28551/? W/System.err:     at com.alphawallet.app.service.KeyService.signWithKeystore(KeyService.java:1080)
2022-04-05 10:50:00.600 27773-28551/? W/System.err:     at com.alphawallet.app.service.KeyService.signData(KeyService.java:377)
2022-04-05 10:50:00.600 27773-28551/? W/System.err:     at com.alphawallet.app.service.KeystoreAccountService.lambda$signMessage$13$com-alphawallet-app-service-KeystoreAccountService(KeystoreAccountService.java:345)
2022-04-05 10:50:00.601 27773-28551/? W/System.err:     at com.alphawallet.app.service.KeystoreAccountService$$ExternalSyntheticLambda14.call(Unknown Source:6)
2022-04-05 10:50:00.601 27773-28551/? W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
2022-04-05 10:50:00.601 27773-28551/? W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2022-04-05 10:50:00.601 27773-28551/? W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2022-04-05 10:50:00.601 27773-28551/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
2022-04-05 10:50:00.601 27773-28551/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
2022-04-05 10:50:00.601 27773-28551/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-04-05 10:50:00.601 27773-28551/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2022-04-05 10:50:00.601 27773-28551/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-04-05 10:50:00.602 27773-28551/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-04-05 10:50:00.602 27773-28551/? W/System.err:     at java.lang.Thread.run(Thread.java:929)
```

**Comment by JamesSmartCell** [comment] 2022-04-05 06:48
Ah it thinks it's a legacy key. OK let me try to fix this, I think I see what went wrong

**Comment by seabornlee** [comment] 2022-07-12 11:28
@JamesSmartCell Can you update your progress with this one?

**Comment by JamesSmartCell** [comment] 2022-10-04 05:36
@hboon This should be fixed now; I fixed another potentially related issue.

**Comment by hboon** [comment] 2022-10-04 05:41
Ok, thanks. I'll close this now, feel free to re-open or re-create another one. I get the impression it fundamentally boils down to one seed/private key not being accessible?

**Closed** 2022-10-04 05:41 UTC
Labels: Bug, High Priority
