### ISSUE TITLE
Crashes: IndexOutOfBoundsException com.alphawallet.app.ui.HomeActivity.getFragment

### ISSUE THREAD

**Issue by seabornlee** [AlphaWallet/alpha-wallet-android#2642] opened 2022-06-06 07:54 UTC
<img width="998" alt="image" src="https://user-images.githubusercontent.com/735708/172119207-25f7c597-4e3c-49fb-96cb-439eecf4b4f5.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/735708/172119332-45eabc9c-6d33-4211-aed5-7d36b4305413.png">

java.lang.IndexOutOfBoundsException: 
  at java.util.Collections$EmptyList.get (Collections.java:4511)
  at com.alphawallet.app.ui.HomeActivity.getFragment (HomeActivity.java:883)
  at com.alphawallet.app.ui.HomeActivity.onWalletName (HomeActivity.java:478)
  at com.alphawallet.app.ui.HomeActivity.$r8$lambda$_y6o_reF_cPqdB4qzNF7C7XNoJg (Unknown Source)
  at com.alphawallet.app.ui.HomeActivity$$ExternalSyntheticLambda15.onChanged (Unknown Source:4)
  at androidx.lifecycle.LiveData.considerNotify (LiveData.java:133)
  at androidx.lifecycle.LiveData.dispatchingValue (LiveData.java:151)
  at androidx.lifecycle.LiveData.setValue (LiveData.java:309)
  at androidx.lifecycle.MutableLiveData.setValue (MutableLiveData.java:50)
  at androidx.lifecycle.LiveData$1.run (LiveData.java:93)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7840)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:985)

**Comment by asif-finimble** [comment] 2022-06-27 11:31
This crashlog is generated on trying to rename the header with currently selected wallet's name/ens-name. Not able to reproduce the issue, but I have put in a try catch block to avoid crashing the app.

**Comment by JamesSmartCell** [comment] 2022-06-30 09:33
Hi @asif-finimble yes I agree It looks like a fragment operation has been pushed before the fragments have been initialised. I guess wrapping in a try block would keep the process running. I don't think we've ever seen this in the wild, but it should be fixed

**Closed** 2022-07-04 22:35 UTC
