### ISSUE TITLE
Make it possible to pass any signable data from the webview to the wallet to be signed

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1556] opened 2020-08-05 05:25 UTC
When considering providing a sign function that can hash by SHA256, first I observed that web3j offered the capacity to sign pre-hashed data

In `Sign.java` (web3j):

    public static SignatureData signMessage(byte[] message, ECKeyPair keyPair) {
        return signMessage(message, keyPair, true);
    }

    public static SignatureData signMessage(byte[] message, ECKeyPair keyPair, boolean needToHash) {
        BigInteger publicKey = keyPair.getPublicKey();
        byte[] messageHash;
        if (needToHash) {
            messageHash = Hash.sha3(message);

Then I realised it takes 12 ayers of calls to reach there. This is a problem since we decided in TS Weekly meeting that data objects are assembled from the web and to be signed later in the user-agent, a process which requires the web layer to be able to pass complex data (not just bytes) to the place very near the actual signing, and during that passage, the data might even be rendered to the user.

questions to @JamesSmartCell are:

1. Did the 8 layers I wrote below correct? I used static code tracing & haven't changed anything to observe the runtime so I could be mistracking in some places;

2. I feel we can have fewer layers. (No I am not going to change anything - I know you would be worried). There is the need for keeping asset keys (requires unlocking) and signing keys (like the one used by the state channel, which lives in memory without unlocking), that can be abstracted in a keyKeeper service; from there you need to handle built-in service calls (e.g. state channel), or JS calls from Token Card, or JS calls from the web. Look like we can remove 2 to 3 layers without affecting flexibility and serviceability?

# Layers inside WebView (before entering Java)

## Layer 1

The web page calls `eth.personal.sign()`

## Layer 2

At certain point in the `app/src/main/res/raw/alphawallet_min.js` this call is captured in a switch-case like this:

````
HookedWalletSubprovider.prototype.handleRequest = function(payload, next, end){
    …
    case 'eth_sign':
      // process normally
      address = payload.params[0]
      message = payload.params[1]
      …
      return

    case 'personal_sign':
      // process normally
      const first = payload.params[0]
      const second = payload.params[1]
      …
      msgParams.chainType = "ETH"
      waterfall([
        // (cb) => self.validatePersonalMessage(msgParams, cb),
        (cb) => self.processPersonalMessage(msgParams, cb),
      ], end)
````

This code is squeezed into `app/src/main/res/raw/alphawallet_min.js` so I can't just paste a link reference. (By the way why do we minify it in the first place? There is no bandwidth saving here since it's local to local).

## Layer 3

In the same file (`app/src/main/res/raw/alphawallet_min.js`) we have this:

````
HookedWalletSubprovider.prototype.processPersonalMessage = function(msgParams, cb) {
  const self = this
  waterfall([
    (cb) => self.approvePersonalMessage(msgParams, cb),
    (didApprove, cb) => self.checkApproval('message', didApprove, cb),
    (cb) => self.signPersonalMessage(msgParams, cb),
  ], cb)
}
````

## Layer 4

This time the call leaves `alphawallet_min.js` and enters `init.js`:

https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/res/raw/init.js#L29

# Layers in the user-agent (not accessible by WebView)

## Layer 5

Which is called from `SignCallbackJSInterface.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/web3/SignCallbackJSInterface.java#L67-L78

## Layer 6

The call is passed to here:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/ui/DappBrowserFragment.java#L846
And when the user confirms, here:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/ui/DappBrowserFragment.java#L1519-L1525

## Layer 7

Which is called from `DappBrowserViewModel.java `:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/viewmodel/DappBrowserViewModel.java#L181-L187

## Layer 8

Which is called from `TransactionRepository.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/repository/TransactionRepository.java#L249-L257

## Layer 9

Which is called from `KeystoreAccountService.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/service/KeystoreAccountService.java#L226

## Layer 10

Which is called from the same file:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/service/KeyService.java#L322

## Layer 11

It's called from `KeyService.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/service/KeyService.java#L1073

## Layer 12

Which is called from `CreateTransactionInteract.java`:
https://github.com/AlphaWallet/alpha-wallet-android/blob/80dfd1b660058b3ff6a820050675cc1060bd1bff/app/src/main/java/com/alphawallet/app/interact/CreateTransactionInteract.java#L27-L37

**Comment by colourful-land** [comment] 2020-08-05 05:39
@hboon Hi I was to add the capacity of signing SHA256 data but when looking at Android it seems a signing call passed 8 layers and in between the layers the data are unpacked, packaged again and baked differently, that is, I can't just add a member to a struct (hash method) and just change the top & bottom layer.

I can still do that (changing about 4 files) but I just want to quickly check if iOS has the same deep layered structure, because if it is the case it is not a task any more, but a project, and it may be better to stop doing this quick fix and integrate it with the attestation signing thing altogether.

A bit of back story: x.509 required the signing method to be flexible and encoded in the attestations - they were first fixed in the 80s but with new cryptography and more powerful computer they eventually have to evolve into a layered structure so they can upgrade the attestation bits without upgrading the whole systems. I think this day will come to Ethereum too (except Ethereum is less well prepared because the signing method is deeply baked into the VM instead of abstracted & compartmentalised).

**Comment by hboon** [comment] 2020-08-05 05:53
@colourful-land There are a few layers, mostly to bridge between the browser and native code, less if it isn't initiated directly from the browser (I imagine not?) . But they are just passing a data blob (a wrapper object around it rather, to indicate how we should sign it) being passed around. Due to the type-safety, we might need to change a few more places, but they should all be flagged by the compiler.

If you (or someone, or me) implement the actual signing implementation, we ought to be able to make it work quite easily.

**Comment by JamesSmartCell** [comment] 2020-08-05 11:06
@colourful-land the path you are showing is incorrect as 'MessagePair' is only used for the QR packaging for rotating QR code. Not sure how you ended up there.

You show the path through the DappBrowser; yes there is a lot of abstraction here, if you like I can show you how the JavaScript intercept and re-route/callback etc works but there are a lot of factors in play.

If you follow the real signing process you'll see it's a lot shallower - dappbrowser isn't involved at any stage, there's no unpacking or repacking (I guess that's dramatic license!) into different formats.

Roughly:

- user is asked to unlock key to produce an unlock event
- transaction is formed using web3j transaction tools
- transaction is passed to keyservice for signing.
- once we have the signed data we send it directly via web3 sending tools (no 'Message pair', no 'unpacking/repacking' etc).
- the same function also writes the pending transaction to realm.

You could reduce the number of calls by doing something like this:

- Duplicate all signing and sending code in every class where it's used, so we can in-line all the unlocking of keys together with all the calls to blockchain (also duplicated). Does this seem like a good idea?

**Comment by JamesSmartCell** [comment] 2020-08-05 11:12
Let me know at high level what you're trying to accomplish and either I can re-interpret it as a spec and farm it out or advise you the best way to accomplish what you're trying to do within the wallet framework, gently leading you to the areas where you can add code.

There is by necessity an amount of abstraction within the wallet code, for purposes of modularisation and de-duplication.

**Comment by colourful-land** [comment] 2020-08-06 00:46
> Let me know at high level what you're trying to accomplish

Create a `Signable` to replace `entity.Message` with the view that later we can derive

- EthereumMessage
- x.509 (including attestations)
- TypedEthereumMessage

And make such an entity pass all the way down to the bottom for web3j to work on.

**Comment by JamesSmartCell** [comment] 2020-08-06 01:21
I reviewed the code with Weiwu - the issue is not so much abstraction but interconnecting fibre. This area still has a lot of now unnecessary layers left over from the original code; which served some purpose originally but now are just connecting services. We're at a position where a lot of those layers could be removed without consequence.

For now however, it's easier to use the signing end point here:

```
class KeystoreAccountService:

    public Single<SignatureFromKey> signTransaction(Wallet signer, byte[] message, long chainId)
    {
        return Single.fromCallable(() -> {
            //byte[] messageHash = Hash.sha3(message);
            SignatureFromKey returnSig = keyService.signData(signer, message);
            returnSig.signature = patchSignatureVComponent(returnSig.signature);
            return returnSig;
        }).subscribeOn(Schedulers.io());
    }
```

However I checked the code it is not accurate for this code to be in this class - the signing key could be HD or Keystore. It would make sense to do a refactor and move this code somewhere more logical.

This can be done later without impacting the current signing work.

**Comment by colourful-land** [comment] 2020-08-06 05:26
- [ ] 1. Replace the current `entity.Message` with a new class `EthereumMessage` which implement a new interface `Signable`. The Interface will eventually help the creation of other signable types, and will be used instead of `EthereumMessage` when feasible, in one of the following classes.

Going to affect classes:

	     src/main/java/com/alphawallet/app/entity/DAppFunction.java
	     src/main/java/com/alphawallet/app/ui/DappBrowserFragment.java
	     src/main/java/com/alphawallet/app/ui/FunctionActivity.java
	     src/main/java/com/alphawallet/app/ui/widget/holder/TokenFunctionViewHolder.java
	     src/main/java/com/alphawallet/app/util/Hex.java
	     src/main/java/com/alphawallet/app/viewmodel/DappBrowserViewModel.java
	     src/main/java/com/alphawallet/app/viewmodel/TokenFunctionViewModel.java
	     src/main/java/com/alphawallet/app/web3/OnSignMessageListener.java
	     src/main/java/com/alphawallet/app/web3/OnSignPersonalMessageListener.java
	     src/main/java/com/alphawallet/app/web3/SignCallbackJSInterface.java
	     src/main/java/com/alphawallet/app/web3/TokenScriptCallbackInterface.java
	     src/main/java/com/alphawallet/app/web3/Web3TokenView.java
	     src/main/java/com/alphawallet/app/web3/Web3View.java
	     src/main/java/com/alphawallet/app/web3/entity/FunctionCallback.java
	     src/main/java/com/alphawallet/app/widget/SignMessageDialog.java

**Comment by JamesSmartCell** [comment] 2020-08-06 06:23
Seems reasonable to me. Let's see the code when it's done!

Can you work on the activity-refactor branch to avoid merge conflicts? There shouldn't be any it will be easier to work on that branch. If you don't like to do that ... well we'll try to pick up the pieces later.

**Comment by colourful-land** [comment] 2020-08-06 06:40
Tasklist:
- [ ] Replace `TypedData`, `Message` with `EthereumMessage`, `EthereumTypedMessage` both implementing `Signable` interface.
- [ ] Make the `Signable` data types penetrate deeper into the facbric layers to near where web3j is.
- [ ] Make a new `Signable` to handle SHA256 signing (later attestation signing will be derived from the same place).

**Comment by JamesSmartCell** [comment] 2021-10-06 04:10
Closing as now complete. The sign packaging is now more coherent.

There is still some abstraction but this is mostly required to deal with the different types of signing allowed (eg Biometric, PIN etc), and the different types of keys (Seed phrase vs Keystore), and the different locking of keys (locked, not locked) and different security chips in the phone (Strongbox vs Samsung Knox vs Generic secure), the difference between API 30 and API24-29 and so on.

**Closed by JamesSmartCell** 2021-10-06 04:10 UTC
