### ISSUE TITLE
File not found exception on TokenScript 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/alpha-wallet-android#1267] opened 2020-04-03 02:43 UTC
2020-04-03 13:38:07.494 11078-11114/io.stormbird.wallet I/System.out: Unknown tag while processing Action: output
2020-04-03 13:38:07.495 11078-11114/io.stormbird.wallet I/System.out: Unknown tag while processing Action: Signature
2020-04-03 13:38:07.507 11078-11115/io.stormbird.wallet I/System.out: ERROR While parsing: /
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err: java.io.FileNotFoundException:  (No such file or directory)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at java.io.FileInputStream.open0(Native Method)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at java.io.FileInputStream.open(FileInputStream.java:231)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:165)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at com.alphawallet.app.service.AssetDefinitionService.addContractAddresses(AssetDefinitionService.java:775)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at com.alphawallet.app.service.AssetDefinitionService.lambda$lDtHUMrqC7OrZQlM1QxqI6khiwg(Unknown Source:0)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at com.alphawallet.app.service.-$$Lambda$AssetDefinitionService$lDtHUMrqC7OrZQlM1QxqI6khiwg.accept(Unknown Source:4)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at io.reactivex.internal.observers.DeferredScalarDisposable.complete(DeferredScalarDisposable.java:82)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:53)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-04-03 13:38:07.508 11078-11115/io.stormbird.wallet W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-04-03 13:38:09.306 11078-11078/io.stormbird.wallet I/System.out: Tickers received: 11

This happens when this shows up:
![unnamed](https://user-images.githubusercontent.com/16630514/78318646-03b3d600-75b1-11ea-89ba-15be7e1b2f57.png)

Followed by:
![Screenshot_2020-04-03-10-36-17-130_io stormbird wallet](https://user-images.githubusercontent.com/16630514/78318661-0f070180-75b1-11ea-87b1-1e5d270394f3.png)

**Comment by JamesSmartCell** [comment] 2020-04-03 03:08
@James-Sangalli Unable to reproduce. Please link script that produces the problem to the issue.

**Comment by James-Sangalli** [comment] 2020-04-03 03:39
[ens.txt](https://github.com/AlphaWallet/alpha-wallet-android/files/4424929/ens.txt)

Supposed to be XML but had to convert it to txt

**Comment by JamesSmartCell** [comment] 2020-04-03 06:47
It's almost identical to an ENS.xml file produced manually, except it has some kind of encoding bug in the declaration of ```var mappingStr = ... ```. Substituting the same code from the subdomainbundle.js file fixes the issue.

However, agree that the error should be reported at the time of dropping the file in, or in a Token Management page.

**Comment by JamesSmartCell** [comment] 2020-04-08 22:28
This should be closed by #1285 and #1273

**Closed by JamesSmartCell** 2020-04-08 22:28 UTC
Labels: bug
