### ISSUE TITLE
Something wrong with HTTPS cert for aw.app

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#1594] opened 2020-09-10 05:45 UTC
macOS:

```
$ curl https://aw.app/api/v1/verifyXMLDSig
```

```
curl: (60) SSL: no alternative certificate subject name matches target host name 'aw.app'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

---

iOS:

```
load failed with error Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “aw.app” which could put your confidential information at risk." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x7fc61a071c00) s: *.execute-api.us-west-1.amazonaws.com i: Amazon>",
    "<cert(0x7fc61a06d400) s: Amazon i: Amazon Root CA 1>",
    "<cert(0x7fc61a06dc00) s: Amazon Root CA 1 i: Starfield Services Root Certificate Authority - G2>",
    "<cert(0x7fc61a06e400) s: Starfield Services Root Certificate Authority - G2 i: Starfield Class 2 Certification Authority>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://aw.app/api/v1/verifyXMLDSig, NSErrorFailingURLStringKey=https://aw.app/api/v1/verifyXMLDSig, NSUnderlyingError=0x6000052628e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x600006d9e910>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9843, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7fc61a071c00) s: *.execute-api.us-west-1.amazonaws.com i: Amazon>",
    "<cert(0x7fc61a06d400) s: Amazon i: Amazon Root CA 1>",
    "<cert(0x7fc61a06dc00) s: Amazon Root CA 1 i: Starfield Services Root Certificate Authority - G2>",
    "<cert(0x7fc61a06e400) s: Starfield Services Root Certificate Authority - G2 i: Starfield Class 2 Certification Authority>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <20B5C122-EBA9-4982-B641-32A364B8E791>.<129>"
```

---

**Comment by colourful-land** [comment] 2020-09-10 05:50
Oh my goodness! This need urgent fixing. Look like something is wrong with the api gateway.

**Comment by colourful-land** [comment] 2020-09-10 06:37
It works for me. 

    $ curl https://aw.app/api/v1/verifyXMLDSig
    {"timestamp":"2020-09-10T06:36:55.907+0000","status":405,"error":"Method Not Allowed","message":"Request method 'GET' not supported","path":"/api/v1/verifyXMLDSig"}

**Comment by colourful-land** [comment] 2020-09-10 06:40
Okay, here is some clue.

There are 2 IP addresses associated with aw.app:
````
$ host aw.app
aw.app has address 54.67.102.112
aw.app has address 54.193.69.210
````
If using 54.67.102.112 there is no error.

If using 54.193.69.210 you get a certificate issue like you described.

**Comment by colourful-land** [comment] 2020-09-10 06:47
Verified that the deletion of the A record is done, only the correct record now shows up
````
$ host aw.app
aw.app has address 54.67.102.112
````

**Comment by hboon** [comment] 2020-09-10 06:49
Seems to work for me now too:

```
$ curl https://aw.app/api/v1/verifyXMLDSig

{"timestamp":"2020-09-10T06:48:08.203+0000","status":405,"error":"Method Not Allowed","message":"Request method 'GET' not supported","path":"/api/v1/verifyXMLDSig"}
```

**Comment by hboon** [comment] 2020-09-15 05:30
Maybe related to work done in  #1593, SSL cert seems to be broken?

```
$ curl https://aw.app
curl: (60) SSL: no alternative certificate subject name matches target host name 'aw.app'
More details here: https://curl.haxx.se/docs/sslcerts.html
```

**Comment by colourful-land** [comment] 2020-09-16 10:25
> Maybe related to work done in #1593, SSL cert seems to be broken?
> 
> ```
> $ curl https://aw.app
> curl: (60) SSL: no alternative certificate subject name matches target host name 'aw.app'
> More details here: https://curl.haxx.se/docs/sslcerts.html
> ```

Yes, this turns out to be a duplicate of #1593 as they share a root cause.

**Closed by colourful-land** 2020-09-16 10:25 UTC

**Comment by colourful-land** [comment] 2020-09-16 10:31
A plausible explanation of this is that the ELB balancer had 2 IP addresses, and they changed one. I (unaware of the root cause of the problem) removed it and leaving it with a working IP address, until they changed it too. As explained in #1593, the correct way to do it is to link the domain aw.app to the ELB balancer INSTEAD OF the IP addresses of the balancer.
