### ISSUE TITLE
The wallet screeen shows wrong information 

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1588] opened 2020-09-07 00:35 UTC
Version: 3.14.2-beta

The screens take some time to load, but the wrong and misleading information that comes in the first few seconds leads to bad user experience:

Examples:
![image](https://user-images.githubusercontent.com/61957841/92338705-7c393880-f0f5-11ea-9a97-540a0c4435e2.png)

![image](https://user-images.githubusercontent.com/61957841/92338743-b276b800-f0f5-11ea-8886-4e2203e9182e.png)

There are many more, may be loading screens design @tomekalphawallet is working on can be the solution

**Comment by JamesSmartCell** [comment] 2020-09-07 03:30
@AW-STJ So in the first few seconds of a new install you are seeing Eth appear as 'TestNet'?

**Comment by tomekalphawallet** [comment] 2020-09-08 11:39
I would like to involve @hboon in this thread. 

I think the best solution could be Skeleton design (animated). 
It is related to the same issue, when you have just imported a wallet with tons of tokens. It might take up to a few minutes for balances to update. For these few minutes, a wallet misleads you. I would say it is better to show a skeleton design than a coin symbol with a wrong balance. 

In the wallet tab, cells can load one by one OR all at once. 
![loading_skeleton](https://user-images.githubusercontent.com/51817359/92471727-50d74c00-f1d0-11ea-8f49-c4205597f488.jpg)


Thoughts?
<img width="781" alt="Screenshot 2020-09-08 at 12 27 09" src="https://user-images.githubusercontent.com/51817359/92471662-343b1400-f1d0-11ea-887a-09224a3aed7f.png">

**Comment by tomekalphawallet** [comment] 2020-09-08 11:41
For the ticket, we can apply the same:
<img width="822" alt="Screenshot 2020-09-08 at 12 35 54" src="https://user-images.githubusercontent.com/51817359/92471805-7401fb80-f1d0-11ea-932e-962151d9fa3f.png">

**Comment by tomekalphawallet** [comment] 2020-09-08 11:42
![example](https://user-images.githubusercontent.com/51817359/92471966-b4fa1000-f1d0-11ea-95e8-24c4f44e5aa9.png)

**Comment by hboon** [comment] 2020-09-09 03:28
Skeleton views and this issue are related but I think they are separate things.

It looks like this issue describes a bug; it's displaying wrong data (mainet displayed as TestNet) temporarily, not outdated data. So it can be fixed by addressing that.

As for skeleton/placeholder views, there are a few considerations:

* generally good
* The SDK for iOS 14 comes with support for showing skeleton views. So it's easy to show it (but the logic to enable it still needs to be built, and we need to rebuild our UI to use it). Long time [1] until we can use it though. But it's validation for the approach. Of course we can build it without relying on the built-in behavior
* they can (only) be used for initial loading, not (easily) when data is outdated; there are technical complications since we don't track how old data is [2], so we can't decide if data is outdated
* they can't be used for TokenScript views, well technically they can, but each TokenScript author has to implement their own

I think it's generally hard to implement it across the app and might not be worth the effort, for now at least. Also checking with Victor on direction, which should be used to weigh such decisions (I have been meaning to ask him, but this suggestion reminded me to actually do it).

If we want to take this discussion further, might be better to move this to a separate issue?

[1] Long time because we have to drop support for <= iOS 13 as well as rebuild the UI that we want to utilize this functionality
[2] I think we should, since it's inherent in the blockchain systems we work with, and we can make good use of it, but it's a lot of work to get there. Some ways it can help: E.g if we know that price is old, we might show it in a different color/contrast so it's still readable, but known to be outdated, or when the user wants to send and empty their wallet, we can make a check if we know the balance is outdated.

**Comment by JamesSmartCell** [comment] 2020-09-15 00:24
@AW-STJ "The screens take some time to load". Please provide context - alone I don't know know what this refers to. Is it a separate issue from the 'Testnet' issue? 

Is this when you click on the token? Or when you first open a new wallet. If the latter - this is caused by the need to 'discover' the tokens on the wallet via examining the Etherscan API return and trying to determine what tokens are in the wallet and is a consequence of the way Ethereum works.

**Comment by AW-STJ** [comment] 2020-09-15 00:55
@JamesSmartCell The time to load that I referred to is when the wallet is first opened. As the Ethereum APIs take some time to load, can we use the loading screens till all the information is loaded correctly and then display the tokens?

From the discussion, feels like this is a separate issue.. so I will raise it as such. We can close this issue when once we resolve the 'TestNet' error and make sure that the information displayed during initial loading during wallet creation is correct.

**Comment by JamesSmartCell** [comment] 2020-09-15 01:16
I see, you're referring to the discovery process, now I understand how this is relevant - calling it loading screens is quite misleading - maybe loading token placeholders. Not quite as catchy but immediately understandable.

**Comment by AW-STJ** [comment] 2020-09-15 02:00
Sorry James.. I see that I was not clear enough. Will try to be more specific.

**Closed** 2020-09-15 02:31 UTC
Labels: bug

**Comment by AW-STJ** [comment] 2020-09-18 00:34
@JamesSmartCell really like how the tokens load for imported wallets. Good one.
