### ISSUE TITLE
Back button in the browser doesn't go to the previous web page

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#1516] opened 2020-07-16 07:06 UTC
Android's back button in the browser doesn't go to the previous web page Instead, it goes to the previous tab. The user has to hit the "Back" button on the upper-left-hand in order to go back. This issue asks it to function the same

You might ask: If we allow the back button behaves like a normal browser, then how does the user go back to the token card the user was at?

The answer is the user can't go to the browser tab unless he leaves the token card he was at first, so there is no token card to go back to. Therefore it should be okay to let back button function as browser back button when in the browser.

The second issue is that the back button will never bring the user back to other tabs if the current user has a long browsing history.

That is true but the user can always switch to other tabs with the bottom row of icons. In the long run, I prefer to think the tabs we have "Wallet, Transactions, Settings" are like browser tab (I know we don't have tabbed browsing yet but we will get there), so back is always done within the current tab.

Sending it to @tomekalphawallet first so if he approves my request, this goes to @ChintanRathod with @AW-STJ in the loop.

**Comment by JamesSmartCell** [comment] 2020-07-20 01:57
This area is plagued with trouble since the beginning. 

The issue is that we're using the browser's built in history but overriding it under certain conditions to get the tabs working correctly with it.

The browser back and forward buttons do actually work exactly as expected within a single session, but when spread out over several sessions there can be inconsistencies, which are probably noticed and manifest as the 'back button not doing I what expect'.

What I propose:

- Back and forward buttons at the top only work the browser back/forward as expected.
- We have a 'home' button that takes the user to the initial wallet screen (currently this is done by clicking on the 'Browser' tab at the bottom, but this is not obvious).

Currently on terminating the app, the app makes a note of where the user was, and re-positions the app to that page. However if the user clicks 'back' then they will go to the home page, which is what I suspect this issue is about.

We can either:

- store the whole history and re-create it (Chrome does this if you force close).
- only store the top page and "short circuit" it back to the home page if back is clicked.
- Always re-set the top screen on each session (as Chrome does if you clean close it).

On desktop you always start a fresh session if you clean closed the browser but on the mobile it re-creates the full stack each time you re-open. So users are probably expecting the same experience.

**Comment by tomekalphawallet** [comment] 2020-07-20 08:46
I can take care of it tomorrow or on Wednesday. I am super busy with DeFi at the moment.

**Comment by colourful-land** [comment] 2020-07-29 14:16
> I can take care of it tomorrow or on Wednesday. I am super busy with DeFi at the moment.

Reminder - now can you do it?

**Comment by hboon** [comment] 2020-07-31 15:15
Reposting a comment I made elsewhere at https://github.com/AlphaWallet/alpha-wallet-android/issues/1547#issuecomment-667157434

For context, hitting a tab button on iOS pops the entire stack. It’s default functionality. We could disable it. BC does.

I suppose Android complicates this a bit more with the concept of a, sometimes, ambiguous but system-wide back button.

**Comment by JamesSmartCell** [comment] 2020-08-03 05:01
> Reposting a comment I made elsewhere at [#1547 (comment)](https://github.com/AlphaWallet/alpha-wallet-android/issues/1547#issuecomment-667157434)
> 
> For context, hitting a tab button on iOS pops the entire stack. It’s default functionality. We could disable it. BC does.
> 
> I suppose Android complicates this a bit more with the concept of a, sometimes, ambiguous but system-wide back button.

I think we're talking about a different issue - this is the forward/back browser specific buttons rather than the OS view stack buttons. The OS buttons should work in harmony with the native OS expectation. I get very frustrated when using iOS exactly because of that behaviour, it keeps chucking me back to the start - which is the OS behaviour. Whereas Android apps should go to the previous activity.

**Comment by hboon** [comment] 2020-08-03 05:08
> I think we're talking about a different issue 

Yes, I posted it in the other issue originally.

> it keeps chucking me back to the start - which I am aware is not an issue as it is the correct OS behaviour.

Off topic now since it's not related, but regarding this: I *think* on iOS, it should only bring people back to the base of the view stack, rather than affect both the view stack and the browser history stack. The latter is quite confusing to many users and hard to "undo". But yes, iOS does both by default.

**Comment by AW-STJ** [comment] 2021-02-03 06:18
@JamesSmartCell : as discussed, it should be problem with the animation that hides the back button while exposing the complete web address. This does not go back to the original form, exposing back button, once the user clicks on address bar.

![image](https://user-images.githubusercontent.com/61957841/106706439-ccd0a580-6643-11eb-8948-0bd93a7b9d69.png)

**Comment by colourfreak** [comment] 2021-02-05 09:00
1. Add a Home Button as I requested in #1596 
2. To collapse the keyboard and escape from typing, you can click anywhere in the pink area.
3. Add "Set as Home Page" and "Change Network" to the menu

<img width="1812" alt="Screenshot 2021-02-05 at 09 58 02" src="https://user-images.githubusercontent.com/51817359/107011964-acfec600-6798-11eb-9e66-87258f124a66.png">

**Comment by colourfreak** [comment] 2021-02-05 09:02
https://zpl.io/ad6wyr7
https://zpl.io/2pwjgno
https://zpl.io/aN6nYn4

**Closed** 2021-02-12 10:57 UTC
