### ISSUE TITLE
Import Wallet/PRIVATE KEY KEYSTORE

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-android#810] opened 2019-08-15 13:48 UTC
![IMAGE 2019-08-15 23:44:44](https://user-images.githubusercontent.com/33795543/63098645-aaae1800-bfb6-11e9-9540-88140b928833.jpg)

The" IMPORT FROM ICLOUD/DROP...." no function and at the wrong place.
It should be under KEYSTORE
![IMAGE 2019-08-15 23:47:26](https://user-images.githubusercontent.com/33795543/63098795-0bd5eb80-bfb7-11e9-9144-f04265ba37bd.jpg)

**Comment by James-Sangalli** [comment] 2019-11-04 00:39
@justindg feel free to tackle this one

**Comment by ronakdave195** [comment] 2020-01-28 05:59
@JamesSmartCell May I request you to confirm if this bug is resolved or is it still open?

**Comment by JamesSmartCell** [comment] 2020-02-10 10:37
@ronakdave195 that's correct, it's not a bug it's how it's meant to function.

I believe this issue has been fixed during UI update.

**Comment by JamesSmartCell** [comment] 2020-02-14 02:15
Fixed in UI upgrade.

**Closed by JamesSmartCell** 2020-02-14 02:15 UTC
Labels: bug
