### ISSUE TITLE
Keep one network label in each token card

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#868] opened 2019-09-19 05:55 UTC
Relates to https://github.com/AlphaWallet/alpha-wallet-ios/issues/1462

There are two network labels only one needs to remain. Kill the 2nd (The one below the title). Keep the 1st (the one right to the title)

![63941384-da791780-caae-11e9-9ee4-d29926d65ed6](https://user-images.githubusercontent.com/548435/65216927-dceef000-daf5-11e9-901a-5d88a54a35fc.jpeg)

**Comment by JamesSmartCell** [comment] 2020-02-04 00:31
fixed in #1133 to tidy recyclerview inconsistency issues caused by the commit.

**Closed** 2020-02-04 02:19 UTC
