### ISSUE TITLE
need to handle USD value hint failure gracefully

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/alpha-wallet-android#888] opened 2019-09-26 07:20 UTC
If somehow the USD value of Ether is not obtainable, currently it shows 0.00USD

(This is observed on the current Google Play Store downloaded version)

It should fall back gracefully, i.e. do not display USD value at all.
![Screenshot_20190926-170748](https://user-images.githubusercontent.com/548435/65666893-f823a780-e081-11e9-883c-5631f813e500.png)

**Comment by ronakdave195** [comment] 2020-02-11 06:42
@James-Sangalli May I kindly request you to confirm if this has been resolved in the latest build version of v2.21.1 RC3? We aren't able to replicate this under the given version.

**Comment by James-Sangalli** [comment] 2020-02-11 11:05
@ronakdave195 I cannot reproduce either

**Closed by James-Sangalli** 2020-02-11 11:05 UTC
Labels: good first issue
