### ISSUE TITLE
Add  a mechanism to collect the crash reports 

### ISSUE THREAD

**Issue by bootingman** [AlphaWallet/alpha-wallet-android#190] opened 2018-05-23 04:03 UTC
Hi, Sangelli,

two users report of crashing when tap AlphaWallet Android app logo after first-time installed on last night,I have collect some info  for reference.

1. Android 8.0 Huawei P10 Plus
2. collecting by asking

If we can't find how they crashed maybe we need to use 3rd party tools #282

**Comment by James-Sangalli** [comment] 2018-09-13 07:35
duplicate of #282

**Comment by colourful-land** [comment] 2018-09-24 08:18
I am trying to find the crash reports from Google:
https://play.google.com/apps/publish/?account=8548546370386799497#AppDashboardPlace:p=io.stormbird.wallet&appid=4973272515950350768

**Comment by colourful-land** [comment] 2018-10-22 13:12
> If we can't find how they crashed maybe we need to use 3rd party tools #282

Yes, we need to. Mark this as a duplicate of #282

**Closed by colourful-land** 2018-10-22 13:12 UTC
